sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - docker-compose up --build -d

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_scrip:
  - docker-compose down
