version: '3.6'

networks:
  backend_network:
    external:
      name: backend_network

services:
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: container@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: changeit
      PGADMIN_SERVER_NAME: pgadmin4
    ports:
      - "5433:80"
    networks:
      - backend_network

