version: '3.6'

services:

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme

  agents:
    build:
      context: .
      args:
        JAR_FILE: /target/agents_e3b-0.0.1-SNAPSHOT.jar
    image: arquisoft/agents_e3b
    ports:
      - "8090:8090"
    links:
      - postgres
